### ISSUE TITLE
service connection permission issue in Decorator

### ISSUE THREAD

**Issue by MasilamaniSeenivasan** [n3wt0n/AzurePipelinesDecoratorSamples#4]
Can you please help me to fix this error, 

"##[error]Pipeline does not have permissions to use the referenced service connection(s) X. For authorization details, refer to https://aka.ms/yamlauthz."

Note: I am using our own custom task inside decorator which require a Service connection permission. how I can grant access to X service connection in Decorator.

**Comment by n3wt0n** [comment]
Hey, sorry I somehow missed this.

There has been a change in Azure DevOps Security, Pipeline permission to a Service Connection have now to be configured through the using the service connection security page. https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#secure-a-service-connection

![image](https://user-images.githubusercontent.com/13121206/141934221-d776ff39-a4ba-4c83-90db-377bb50f7700.png)

**Comment by MasilamaniSeenivasan** [comment]
Thanks a lot for the input.

Also I find that and we can use below DevOps API to automate this.

Method type : PATCH
API URL : https://{orgname}.visualstudio.com/{projectname}/_apis/pipelines/pipelinePermissions/endpoint/{endpointID}
Request body:
{
    "resource": {
        "type": "endpoint",
        "id": "<your endpoint id>"
    },
    "pipelines": [],
    "allPipelines": {
        "authorized": true,
        "authorizedBy": null,
        "authorizedOn": null
    }
}
