### ISSUE TITLE
Help needed! how to skip decorator injection when a Job runs in a specific pool

### ISSUE THREAD

**Issue by MasilamaniSeenivasan** [n3wt0n/AzurePipelinesDecoratorSamples#6]

**Comment by n3wt0n** [comment]
Unfortunately the Pool name or any pool-related information are not propagated to the Pipelines run, so there is no way to achieve this.

You could try and filter on `Agent.Name` if you have a specific naming convention you can rely upon

**Comment by MasilamaniSeenivasan** [comment]
Thanks for the confirmation and input.
